### ISSUE TITLE
Doesn't work on El Capitan

### ISSUE THREAD

**Issue by nicelifeBS** [PeregrineLabs/Ecosystem#10]
When I run the alias or manually the python command I get this:

```
$ eneed maya2016
-bash: /tmp/ecoset: line 1: syntax error near unexpected token `('
-bash: /tmp/ecoset: line 1: `Unable to resolve all of the required tools (!:1 is missing), please check your list and try again!'
/usr/local/Ecosystem
$ ecosystem.py --setenv --tools maya2016 > /tmp/ecoset; source /tmp/ecoset
-bash: setenv: command not found
-bash: setenv: command not found
-bash: setenv: command not found
-bash: setenv: command not found
```

Looks like the argument parsing doesn't work with bash shell which is the default on OSX. Which also explains why setenv is not working. Also I really doubt that the whole system will work since it relies on LD and DYLD_LIBRARY_PATH which is disabled since El Capitan.

**Comment by colindoncaster** [comment]
You need to use the tcsh shell, not bash.
