### ISSUE TITLE
Unexpected environment is being defined and various other issues.

### ISSUE THREAD

**Issue by KelSolaar** [PeregrineLabs/Ecosystem#12]
Hi,

This is happening with the `develop` branch and I'm probably not understanding some of the stuff. I have created two simple files for tests as follows:

**ocio_configuration.env**
```python
{
    'tool': 'ocio_configuration',
    'version': '',
    'platforms': ['windows'],
    'requires': [],
    'environment':
        {
        'OCIO': {'windows': 'D:\OCIO\config.ocio'},
    }
}
```

**nuke_10_0.env**
```python
{
    'tool': 'nuke',
    'version': '10.0',
    'platforms': ['windows'],
    'requires': ['ocio_configuration'],
    'environment':
        {
        'NUKE_MAJOR_VERSION': '10.0',
        'NUKE_MINOR_VERSION': '5',
        'NUKE': {'windows': 'C:/Program Files/Nuke${NUKE_MAJOR_VERSION}v${NUKE_MINOR_VERSION}', },
        'NUKE_VERSION': 'Nuke${NUKE_MAJOR_VERSION}v${NUKE_MINOR_VERSION}',
        'NUKEX_VERSION': 'NukeX${NUKE_MAJOR_VERSION}v${NUKE_MINOR_VERSION}',
        'PATH': {'windows': '${NUKE}'},
    },
}
```

So my initial basic assumption would be that a command such as:

> eco -r nuke10.0

Would run Nuke but unfortunately I get an error:

```cmd
'nuke10.0' is not recognized as an internal or external command,
operable program or batch file.
```

I need to add the requirement as per the documentation to actually have it launching:

> eco -t nuke10.0 -r nuke10.0

Except if I missed something obvious it seems to defeat the purpose of dependency solving, which leads me to the next train of issues:

I took a look at the environment being injected before launching Nuke and I noticed that the `ocio_configuration` requires seem to be ignored because the variable is set to my original system defined value, thus I have to add manually the requirement which is again defeating dependency solving:

> eco -t nuke10.0,ocio_configuration -r nuke10.0

Which in turns resulted of concatenation of the system variable plus the one defined in the **ocio_configuration.env** file:

```cmd
Warning - invalid OpenColorIO config file D:/OCIO/config.ocio;D:/Tools/OCIO/config.ocio specified by OCIO environment variable!
OCIO features will be unavailable for this session.
```

Something I don't get is why the environment doesn't start blank but inherits the system and user variables? If I print `os.environ` just before [call_process](https://github.com/PeregrineLabs/Ecosystem/blob/develop/bin/ecosystem.py#L519), I have a fat list of environment variables which are exactly the ones defined in the system and my user profile, plus the Ecosystem ones. My expectations in that regard were like this by the way ;)

![image](https://cloud.githubusercontent.com/assets/99779/22913856/3ad6136a-f2d2-11e6-8e41-83d563715c5f.png)

Bests,

Thomas

**Comment by mgcollie** [comment]
Thomas how would you know what environment variables are safe to remove?

**Comment by thomasmansencal** [comment]
There are some system one that you need to keep such as $PATH, $USER, etc... You would need to whitelist them depending on your system but I would trim anything else not needed to run it or you start with an absolutely bare and clean system which is maybe what is implied in the *always start fresh* sentence in the above slide.

**Comment by mgcollie** [comment]
Wouldn't this require a low level knowledge of all the environment variables being used by any script/program/library that would exist under the new context so you didn't accidentally wipe out something that one of them required?

**Comment by thomasmansencal** [comment]
I think that you need that knowledge anyway to avoid issues when combining multiple packages together.

**Comment by colindoncaster** [comment]
We ensure that our system environment is clean and the assumption is that users do too - as perviously stated we can't "unset" variables.  

Whenever we install new versions of the applications we use it's common housekeeping to open up our system variables and remove anything they might automatically set.
