### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by mottosso** [PeregrineLabs/Ecosystem#5]
I've had my eyes on this since it got shot across the interwebs and thought it looked interesting, but wasn't in a position to make use of it at the time. Is this still in development? Also, what are your thoughts on Rez as an alternative?

Thanks

**Comment by jasonfairley** [comment]
Hello,

Yes this is still being developed. Rez isn't available for Windows which is why I have been looking at Ecosystem in instead. There is a Google Group for Ecosystem here: https://groups.google.com/forum/?hl=en-GB#!forum/ecosystem-env

**Comment by thomasmansencal** [comment]
Hi,

Bumping that ticket, what is the current status of the project? I have seen a https://github.com/PeregrineLabs/Ecosystem/tree/feature/refactor branch that is fairly active.

I would like to evaluate the tool but I'm not sure which branch I should use for that.

Bests,

Thomas

**Comment by colindoncaster** [comment]
Hi Thomas, 

Use develop for now and in the coming weeks we'll be providing  a new release which includes the refactor branch. 

Thank you

**Comment by thomasmansencal** [comment]
@colindoncaster : Thanks!

Both branches seems to be working!

I have quite a few questions already :) I'm assuming the Google Group is the best place to ask those.
